// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectGoogle() {
  return window['go']['main']['App']['DisconnectGoogle']();
}

export function GetGoogleConnectionStatus() {
  return window['go']['main']['App']['GetGoogleConnectionStatus']();
}

export function ListGoogleDestinations() {
  return window['go']['main']['App']['ListGoogleDestinations']();
}

export function ListGoogleDriveFolder(arg1) {
  return window['go']['main']['App']['ListGoogleDriveFolder'](arg1);
}

export function StartGoogleConnect() {
  return window['go']['main']['App']['StartGoogleConnect']();
}

export function SubmitSchedule(arg1) {
  return window['go']['main']['App']['SubmitSchedule'](arg1);
}
