// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisconnectGoogle():Promise<main.GoogleConnectionStatus>;

export function GetGoogleConnectionStatus():Promise<main.GoogleConnectionStatus>;

export function ListGoogleDestinations():Promise<main.GoogleDestinationOptions>;

export function ListGoogleDriveFolder(arg1:string):Promise<main.GoogleDriveFolderContent>;

export function StartGoogleConnect():Promise<main.GoogleConnectionStatus>;

export function SubmitSchedule(arg1:main.SchedulePayload):Promise<main.ScheduleSubmitResult>;
